# Generated by Django 5.1 on 2024-10-30 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tienda',
            fields=[
                ('id_tienda', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=50)),
                ('correo_electronico', models.CharField(max_length=50)),
                ('horario', models.CharField(max_length=50)),
                ('tipo_de_producto', models.CharField(max_length=50)),
            ],
        ),
    ]
